name: Scheduled PR Merge
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

  schedule:
    # https://crontab.guru/#*/5_*_*_*_*  “At every 5th minute.”
    - cron: '*/5 * * * *'

jobs:
  scheduled_PR_Merge_job:
    name: Scheduled PR Merge Main Job
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      mergedPRs: ${{ steps.mainActionStep.outputs.MPR_LIST }}
      mergeFailPR: ${{ steps.mainActionStep.outputs.MC_PR_NO }}
    steps:
      - id: mainActionStep
        uses: VaibhavChidrawar/merge-schedule-action@env-var
        with:
          merge_method: merge
          time_zone: "Asia/Tokyo"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  slack_notification_job:
    name: Slack Notification Job
    runs-on: ubuntu-latest
    needs: scheduled_PR_Merge_job
    steps:
      - run: echo ${{needs.scheduled_PR_Merge_job.outputs.mergedPRs}} ${{needs.scheduled_PR_Merge_job.outputs.mergeFailPR}}
