name: Scheduled PR Merge
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

  schedule:
    # https://crontab.guru/#*/5_*_*_*_*  “At every 5th minute.”
    - cron: '*/5 * * * *'

jobs:
  merge_schedule_job:
    name: Scheduled PR Merge Main Job
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      output1: ${{ steps.step1.outputs.MC_PR_NO_NEW }}
      output2: ${{ steps.step1.outputs.MC_PR_NO }}
    steps:
      - id: step1
        uses: VaibhavChidrawar/merge-schedule-action@env-var
        with:
          merge_method: merge
          time_zone: "Asia/Tokyo"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  job2:
    runs-on: ubuntu-latest
    needs: merge_schedule_job
    steps:
      - run: echo ${{needs.merge_schedule_job.outputs.output1}} ${{needs.merge_schedule_job.outputs.output2}}
